# Generated by Django 4.1.7 on 2023-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0006_big_equipment_type_cannula_equipment_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="big",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="cannula",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="endotrachealtube",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="fluid",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="gauze",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="gloves",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="laryngoscopeblade",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="lttube",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="medicalequipment",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="nasopharyngealtube",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="needle",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="oropharyngealtube",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="oxygenmask",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="sterilegloves",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="syringe",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="ventilationmask",
            name="equipment_type",
        ),
        migrations.AlterField(
            model_name="drug",
            name="dosage_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pills", "Pills"),
                    ("Nebulizer", "Nebulizer"),
                    ("Injection", "Injection"),
                    ("Ointment / Gel", "Ointment / Gel"),
                    ("Areosol", "Areosol"),
                    ("Rectal enema", "Rectal enema"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
