version: "3"
services:
  web:
    container_name: web_warehouse
    build:
      context: .
      dockerfile: web.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - db
    networks:
      - network_no_internet
      - network_internet

  db:
    container_name: db_warehouse
    image: postgres:16
    environment:
      POSTGRES_DB: db_warehouse
      POSTGRES_USER: db_warehouse
      POSTGRES_PASSWORD: db_warehouse
    #    ports:
    #      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - network_no_internet

volumes:
  pg_data:

networks:
  network_internet:
    driver: bridge
  network_no_internet:
    driver: bridge
    internal: true
