# Generated by Django 4.1.7 on 2023-04-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staffmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="image",
            field=models.ImageField(
                blank=True, default="media/grm_logo.jpg", null=True, upload_to=""
            ),
        ),
    ]
