# Generated by Django 4.1.7 on 2023-05-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0006_staffmodel_can_edit_alter_staffmodel_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmodel",
            name="can_edit",
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="image",
            field=models.ImageField(
                default="grm_logo.png",
                help_text="Your profile image",
                upload_to="profile_pictures",
            ),
        ),
    ]
