# Generated by Django 4.2.6 on 2024-01-07 16:28

import containers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Backpack - ALS", "Backpack - ALS"),
                            ("Backpack - ALS Ampoule", "Backpack - ALS Ampoule"),
                            ("Backpack - R1", "Backpack - R1"),
                            ("Bag - R1", "Bag - R1"),
                            ("Main warehouse", "Main warehouse"),
                            ("Special / Other", "Special / Other"),
                            ("Storage Drawer - hospital", "Storage Drawer - hospital"),
                            ("Trauma Wall - ALS", "Trauma Wall - ALS"),
                            ("Trauma Wall - hospital", "Trauma Wall - hospital"),
                            ("Trunk - ALS", "Trunk - ALS"),
                            ("Trunk - ALS Ampoule", "Trunk - ALS Ampoule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentilationMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("Child", "Child"), ("Adult", "Adult")], max_length=20
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="ventilation_mask",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Syringe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "volume",
                    models.CharField(
                        choices=[
                            ("1ml", "1ml"),
                            ("2ml", "2ml"),
                            ("5ml", "5ml"),
                            ("10ml", "10ml"),
                            ("20ml", "20ml"),
                            ("50ml", "50ml"),
                            ("100ml", "100ml"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="syringe",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SterileGloves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("6.0", "6.0"),
                            ("6.5", "6.5"),
                            ("7.0", "7.0"),
                            ("7.5", "7.5"),
                            ("8.0", "8.0"),
                            ("8.5", "8.5"),
                            ("9.0", "9.0"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="sterile_gloves",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OxygenMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Nasal cannula", "Nasal cannula"),
                            ("Simple mask", "Simple mask"),
                            ("Reservoir mask", "Reservoir mask"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("Child", "Child"), ("Adult", "Adult")], max_length=20
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="oxygen_mask",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OropharyngealTube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("000", "000"),
                            ("00", "00"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="oropharyngeal_tube",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Needle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Orange - 0.5mm", "Orange - 0.5mm"),
                            ("Blue - 0.6mm", "Blue - 0.6mm"),
                            ("Black - 0.7mm", "Black - 0.7mm"),
                            ("Green - 0.8mm", "Green - 0.8mm"),
                            ("Yellow - 0.9mm", "Yellow - 0.9mm"),
                            ("Beige - 1.1mm", "Beige - 1.1mm"),
                            ("Pink - 1.2mm", "Pink - 1.2mm"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="needle",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NasopharyngealTube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("5.0", "5.0"),
                            ("5.5", "5.5"),
                            ("6.0", "6.0"),
                            ("6.5", "6.5"),
                            ("7.0", "7.0"),
                            ("7.5", "7.5"),
                            ("8.0", "8.0"),
                            ("8.5", "8.5"),
                            ("9.0", "9.0"),
                            ("9.5", "9.5"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="nasopharyngeal_tube",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="medical_equipment",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LtTube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Clear #0", "Clear #0"),
                            ("White #1", "White #1"),
                            ("Green #2", "Green #2"),
                            ("Orange #2.5", "Orange #2.5"),
                            ("Yellow #3", "Yellow #3"),
                            ("Red #4", "Red #4"),
                            ("Purple #5", "Purple #5"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="lt_tube",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LaryngoscopeBlade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="laryngoscope_blade",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gloves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="gloves",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gauze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1/4m^2", "1/4m^2"),
                            ("1/2m^2", "1/2m^2"),
                            ("1m^2", "1m^2"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="gauze",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Fluid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "volume",
                    models.CharField(
                        choices=[
                            ("5ml", "5ml"),
                            ("10ml", "10ml"),
                            ("20ml", "20ml"),
                            ("50ml", "50ml"),
                            ("100ml", "100ml"),
                            ("250ml", "250ml"),
                            ("500ml", "500ml"),
                            ("1000ml", "1000ml"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="fluid",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EndotrachealTube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("2.5", "2.5"),
                            ("3.0", "3.0"),
                            ("3.5", "3.5"),
                            ("4.0", "4.0"),
                            ("4.5", "4.5"),
                            ("5.0", "5.0"),
                            ("5.5", "5.5"),
                            ("6.0", "6.0"),
                            ("6.5", "6.5"),
                            ("7.0", "7.0"),
                            ("7.5", "7.5"),
                            ("8.0", "8.0"),
                            ("8.5", "8.5"),
                            ("9.0", "9.0"),
                            ("9.5", "9.5"),
                            ("10.0", "10.0"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="endotracheal_tube",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "active_substance",
                    models.CharField(
                        choices=[
                            ("Acidum acetylsalicylicum", "Acidum acetylsalicylicum"),
                            ("Acidum tranexamicum", "Acidum tranexamicum"),
                            ("Adenosinum", "Adenosinum"),
                            ("Amiodaroni hydrochloridum", "Amiodaroni hydrochloridum"),
                            ("Aqua pro injectione", "Aqua pro injectione"),
                            ("Atropini sulfas", "Atropini sulfas"),
                            ("Budesonidum", "Budesonidum"),
                            (
                                "Calcii chloridum dihydricum",
                                "Calcii chloridum dihydricum",
                            ),
                            ("Captoprilum", "Captoprilum"),
                            ("Clemastinum", "Clemastinum"),
                            ("Clonazepam", "Clonazepam"),
                            ("Clopidogrelum", "Clopidogrelum"),
                            ("Dexamethasoni phosphas", "Dexamethasoni phosphas"),
                            ("Diazepamum", "Diazepamum"),
                            (
                                "Drotaverini hydrochloridum ",
                                "Drotaverini hydrochloridum ",
                            ),
                            ("Epinephrinum", "Epinephrinum"),
                            ("Fentanylum", "Fentanylum"),
                            ("Flumazenilum", "Flumazenilum"),
                            ("Furosemidum", "Furosemidum"),
                            ("Glucagoni hydrochloridum", "Glucagoni hydrochloridum"),
                            ("Glukoza 20%", "Glukoza 20%"),
                            ("Glukoza 40%", "Glukoza 40%"),
                            ("Glukoza 5%", "Glukoza 5%"),
                            ("Glyceroli trinitras", "Glyceroli trinitras"),
                            ("Hepariunum natricum", "Hepariunum natricum"),
                            ("Hydrocortisonum", "Hydrocortisonum"),
                            ("Hydroxyzinum", "Hydroxyzinum"),
                            ("Hyoscini butylbromidum", "Hyoscini butylbromidum"),
                            ("Ibuprofenum", "Ibuprofenum"),
                            ("Ketamine hydrochloride", "Ketamine hydrochloride"),
                            ("Ketoprofenum", "Ketoprofenum"),
                            ("Lidocaini hydrochloridum", "Lidocaini hydrochloridum"),
                            ("Magnesii sulfas", "Magnesii sulfas"),
                            ("Mannitolum", "Mannitolum"),
                            ("Metamizolum natricum", "Metamizolum natricum"),
                            ("Metoclopramidum", "Metoclopramidum"),
                            ("Metoprololi tartras", "Metoprololi tartras"),
                            ("Midazolamum", "Midazolamum"),
                            ("Morphini sulfas", "Morphini sulfas"),
                            ("Naloxoni hydrochloridum", "Naloxoni hydrochloridum"),
                            ("Natrii chloridum 0,9%", "Natrii chloridum 0,9%"),
                            (
                                "Natrii hydrogenocarbonas 8,4%",
                                "Natrii hydrogenocarbonas 8,4%",
                            ),
                            ("Nitrendipinum", "Nitrendipinum"),
                            ("Ondansetronum", "Ondansetronum"),
                            ("Optilyte", "Optilyte"),
                            ("Pantoprazolum", "Pantoprazolum"),
                            ("Paracetamolum", "Paracetamolum"),
                            ("Plasmalyte", "Plasmalyte"),
                            ("Polstigminum", "Polstigminum"),
                            ("Propofolum", "Propofolum"),
                            ("Rocuronium", "Rocuronium"),
                            ("Salbutamolum", "Salbutamolum"),
                            ("Solutio Ringeri", "Solutio Ringeri"),
                            ("Suxamethonii chloridum", "Suxamethonii chloridum"),
                            ("Thiethylperazinum", "Thiethylperazinum"),
                            ("Ticagrelor", "Ticagrelor"),
                            ("Urapidilum", "Urapidilum"),
                        ],
                        max_length=30,
                    ),
                ),
                ("psychotropic_or_narcotic", models.BooleanField(default=False)),
                (
                    "dosage_form",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pills", "Pills"),
                            ("Nebulizer", "Nebulizer"),
                            ("Injection", "Injection"),
                            ("Ointment / Gel", "Ointment / Gel"),
                            ("Areosol", "Areosol"),
                            ("Rectal enema", "Rectal enema"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="drug",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cannula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Purple - 26G", "Purple - 26G"),
                            ("Yellow - 24G", "Yellow - 24G"),
                            ("Blue - 22G", "Blue - 22G"),
                            ("Pink - 20G", "Pink - 20G"),
                            ("Green - 18G", "Green - 18G"),
                            ("White - 17G", "White - 17G"),
                            ("Gray - 16G", "Gray - 16G"),
                            ("Orange - 14G", "Orange - 14G"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="cannula",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BIG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Red - child", "Red - child"),
                            ("Blue - adult", "Blue - adult"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        default=containers.models.Container.get_main_container,
                        null=True,
                        on_delete=models.SET(
                            containers.models.Container.get_main_container
                        ),
                        related_name="big",
                        to="containers.container",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
