# Generated by Django 4.1.7 on 2023-09-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0007_remove_big_equipment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="name",
            field=models.CharField(
                choices=[
                    ("Backpack - ALS", "Backpack - ALS"),
                    ("Backpack - ALS Ampoule", "Backpack - ALS Ampoule"),
                    ("Backpack - R1", "Backpack - R1"),
                    ("Bag - R1", "Bag - R1"),
                    ("Main warehouse", "Main warehouse"),
                    ("Special / Other", "Special / Other"),
                    ("Storage Drawer - hospital", "Storage Drawer - hospital"),
                    ("Trauma Wall - ALS", "Trauma Wall - ALS"),
                    ("Trauma Wall - hospital", "Trauma Wall - hospital"),
                    ("Trunk - ALS", "Trunk - ALS"),
                    ("Trunk - ALS Ampoule", "Trunk - ALS Ampoule"),
                ],
                max_length=50,
            ),
        ),
    ]
