# Generated by Django 4.1.7 on 2023-04-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmodel",
            name="image",
            field=models.ImageField(default="media/grm_logo.jpg", upload_to=""),
        ),
    ]
