# Generated by Django 4.1.7 on 2023-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_alter_staffmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="image",
            field=models.ImageField(default="staff/grm_logo.jpg", upload_to="staff"),
        ),
    ]
