# Generated by Django 4.1.7 on 2023-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_alter_staffmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmodel",
            name="can_edit",
            field=models.BooleanField(
                default=False, help_text="User can edit containers etc"
            ),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="image",
            field=models.ImageField(
                default="grm_logo.jpg",
                help_text="Your profile image",
                upload_to="profile_pictures",
            ),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="position",
            field=models.CharField(
                blank=True, help_text="Role in GRM", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="qualifications_expiration_date",
            field=models.DateField(
                blank=True, help_text="Expiration date of license", null=True
            ),
        ),
    ]
