# Generated by Django 4.1.7 on 2023-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0007_remove_staffmodel_can_edit_alter_staffmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="image",
            field=models.ImageField(
                default="grm_logo.jpg",
                help_text="Your profile image",
                upload_to="profile_pictures",
            ),
        ),
    ]
