# Generated by Django 4.1.7 on 2023-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_alter_staffmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmodel",
            name="can_edit",
            field=models.BooleanField(
                default=False, help_text="User can edit containers etc"
            ),
        ),
    ]
