# Generated by Django 4.1.7 on 2023-06-11 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0009_staffmodel_can_edit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmodel",
            name="can_edit",
        ),
    ]
